idf_component_register(
    SRCS
        "bos_server_registration.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        bos_convergence_aggregator
        bos_time
        esp_event
        esp_http_client
        esp_netif
        esp_timer
        json
        mdns
        nvs_flash
        protocol_examples_common
)
